### ISSUE TITLE
[Ebook Words] Create list of words

### ISSUE THREAD

**Issue by whattablackhole** [whattablackhole/rslang-archive-#11]
Use mock data from db or from restful api.
Ideas: word item component is dumb and word list component is smart.Think about audio service or how to play sounds...

**Comment by kastrubait** [comment]
Additionally created  tasks:
- [x] the home page of the tutorial (issue https://github.com/whattablackhole/rslang/issues/35)
- [x] collections page (issue https://github.com/whattablackhole/rslang/issues/36)
