### ISSUE TITLE
meet 25.03,  for discuss:

### ISSUE THREAD

**Issue by kastrubait** [whattablackhole/rslang-archive-#22]
1. refactoring the project structure
2. best practice: service
2. design layout approval
3. style guide agreement
4. distribution of project tasks between participants

**Comment by kastrubait** [comment]
5. I think it is worth adding a small description of the task. For example so

![image](https://user-images.githubusercontent.com/60570588/112386392-e916c780-8d01-11eb-8b3d-6ec9ae79b261.png)

**Comment by coriander31415** [comment]
7. Q: where will we take Complexity level of Words?
8. Proposal for teamwork meetings organisation: 
 - make calls daily, but limit the time to 30 minutes (set timer)
 - limit discussion to the issues which are the meeting plan
 - Team Lead (or someone else) to control the above points

**Comment by Anntol** [comment]
Eslint is not working "in process"
