### ISSUE TITLE
[Games] Start preloader + Finish statistics

### ISSUE THREAD

**Issue by coriander31415** [whattablackhole/rslang-archive-#41]
- [ ] Start screen of Games 
- [ ] Common components:
    - Start preloader
    - Finish statistics - https://raw.githubusercontent.com/rolling-scopes-school/tasks/2983a7b386dd7335969f5b227457aee4680c4868/tasks/rslang/images/rslang11.png

![image](https://user-images.githubusercontent.com/70798768/112722120-4aac8100-8f10-11eb-89b0-ed190c1a98c5.png)

**Comment by whattablackhole** [comment]
Game countdown timers animation: 
https://codepen.io/suez/pen/dXbBGp
https://codepen.io/FlorinPop17/pen/LzYNWa
https://codepen.io/matevegh/pen/GZVqLL
Game end animation:
https://codemyui.com/circular-water-fill-loading-animation/

**Comment by whattablackhole** [comment]
onLoading:
https://codemyui.com/git-kraken-inspired-rotate-loading-animation/
