### ISSUE TITLE
[App] Suggest logo 

### ISSUE THREAD

**Issue by whattablackhole** [whattablackhole/rslang-archive-#47]
Put here your variants

**Comment by coriander31415** [comment]
![image](https://user-images.githubusercontent.com/70798768/112769434-96068280-9029-11eb-8f61-97be0721e530.png) - looks similiar to our app

https://reallang.com/ - svg is dowloadable, and could be editable in Figma

**Comment by kastrubait** [comment]
And my version)) 

![white_blue](https://user-images.githubusercontent.com/60570588/113453670-26b8d600-940f-11eb-9767-1c51c9fae428.png)

Below, under the line, there may be a slogan. In Russian something like this: "учит, развлекает, зарабатывать помогает", the English version has not yet been invented.

**Comment by superpuper777** [comment]
> ![image](https://user-images.githubusercontent.com/70798768/112769434-96068280-9029-11eb-8f61-97be0721e530.png) - looks similiar to our app
> 
> https://reallang.com/ - svg is dowloadable, and could be editable in Figma

I like it!
