### ISSUE TITLE
[Pre-development] Create Figma Design MVP

### ISSUE THREAD

**Issue by whattablackhole** [whattablackhole/rslang-archive-#7]
Link to Figma: https://www.figma.com/file/4MZRVJ9ZwbFlq6OAZPNqkF/rslang-t4?node-id=0%3A1

### 1. Basic structure (b/w):

- [x] Main page
- [x] EBook 
- [x] Vocabulary
- [x] About page
- [x] Statistics
- [x] Settings
- [x] Games:
     - [x] 'Savanah' (screenshot)
     - [x] 'Audio Call' (screenshot)
     - [x] 'Sprint' (screenshot)
     - [x] 'Find a Pair' (screenshot)
- [x] Header
- [x] Footer
- [x] Menu navigation
- [x] Header navigation
- [x] List of words in different components
- [x] Word card

### 2. Design 

- [x] color palette (Material theme Indigo&pink)
- [x] other assets
- [x] design components
- [x] use Materal?? (remember the issues with editing Material styles!)

---

## Исходные данные

- [x] 3600 слов = 6 коллекций = 30 страниц = 20 слов на странице

## Структура приложения

- главная страница приложения
- электронный учебник со словарём
- мини-игры "Саванна", "Аудиовызов", "Спринт", "Своя игра"
- страница статистики

### Главная страница приложения

- выполняет функцию промо-страницы, её оформление определяет первое впечатление о приложении
- главная страница приложения содержит:
- [x] меню с навигацией по учебнику, ссылками на мини-игры и статистику (Header) 
- [x] Меню или иконка меню отображается на всех страницах приложения
- [x] описание возможностей и преимуществ приложения
- [x] небольшое (5-7 минут) видео с демонстрацией работы приложения
- [x] раздел "О команде" с фото и ссылками на гитхабы всех участников команды, описанием вклада в разработку приложения каждого из них. При желании данный раздел можно вынести в отдельную страницу
- [x]  footer со ссылками на гитхабы авторов приложения, год создания приложения, [логотип курса](https://rs.school/images/rs_school_js.svg) со [ссылкой на курс](https://rs.school/js/). footer отображается на всех страницах приложения за исключением мини-игр.

### Электронный учебник

- [x] электронный учебник состоит из шести разделов, которым соответствуют шесть групп слов коллекции исходных данных. 
- [x] В каждом разделе 30 страниц. 
На каждой странице выводится:
  - [x] меню или иконка меню
  - [x] иконка настроек
  - [x] список из 20 слов 
  - [x] ссылки на мини-игры "Саванна", "Аудиовызов", "Спринт", "Своя игра" для повторения изученных слов
  - [x] навигация по страницам со стрелками для перехода к следующей и предыдущей страницам и номером текущей страницы
  - [x] также необходимо продумать навигацию по шести разделам учебника 
  - и предусмотреть небольшие различия в оформлении каждого раздела. Например, можно использовать для каждого раздела индикатор определённого цвета - _to be defined by user responsible for this component_
  - [x] при перезагрузке страницы открывается последняя открытая страница приложения
- #### Настройки
  - в настройках учебника у пользователя есть возможность указать:
  - [x]  нужно ли отображать в списке слов перевод изучаемого слова и перевод предложений с ним
  - [x] нужно ли отображать возле каждого слова кнопки, при клике по которым данное слово добавляется в раздел словаря "Сложные слова" или "Удалённые слова"
- #### Список слов
  - для каждого слова отображается:
    - [x] само слово, его транскрипция, его перевод
    - [x] предложение с объяснением значения изучаемого слова, его перевод
    - [x] предложение с примером использования изучаемого слова, его перевод
    - [x] картинка-ассоциация к изучаемому слову
    - [x] иконка аудио при клике по которой **последовательно** (???) звучит произношение изучаемого слова, произношение предложения с объяснением его значения, произношение предложения с примером его использования 
    - [x] кнопки, при клике по которым изучаемое слово добавляется в разделы словаря "Сложные слова" или "Удалённые слова"
    - [x] результат изучения/повторения слова в мини-играх (???)
    - [x] если слово добавлено в раздел словаря "Сложные слова", оно остаётся на странице учебника, и его стиль изменяется или возле него выводится индикатор, указывающий, что оно относится к сложным словам
    - [x] если слово добавлено в раздел словаря "Удалённые слова", оно удаляется со страницы учебника. Если пользователь удалит со страницы все слова, страница удаляется
- #### Словарь
  - [x] словарь является частью учебника. В словаре есть разделы "Изучаемые слова", "Сложные слова", "Удалённые слова" !!! 
  - [x] в раздел "Изучаемые слова" попадают слова, которые были задействованы в мини-играх, если мини-игры открывались кликом по ссылке на странице учебника или на странице раздела словаря "Сложные слова". Также в раздел "Изучаемые слова" попадают слова, которые пользователь отметил как сложные. Возле сложных слов есть индикатор или они выделены стилем, так же, как и на странице учебника
   - [x] возле каждого слова в разделе "Изучаемые слова" указывается результат изучения - сколько раз слово было правильно угадано в мини-играх, сколько раз пользователь ошибался
    - [x] для каждого раздела **и каждой страницы учебника** указывается количество изучаемых слов и общий результат их изучения
    - в разделы словаря "Сложные слова" и "Удалённые слова" слова попадают, если пользователь кликнул по соответствующим кнопкам возле слов на страницах учебника
    - [x] страницы разделов словаря "Сложные слова" и "Удалённые слова" выглядят точно так же, как страницы учебника: формируются страницы, на каждой из которых список из 20 слов, создаётся новая страница, 
    - [x] **на страницах есть ссылки на мини-игры для повторения слов** . 
    - [x] Слова из разных разделов учебника попадают на разные страницы, на странице есть **индикатор**, указывающий, к какому разделу учебника она относитеся. Если слов больше 20, создаётся новая страница. 
    - [x] Единственное отличие в списке слов вместо кнопок, при клике по которым изучаемое слово добавляется в разделы словаря "Сложные слова" или "Удалённые слова", в словаре возле слова отображается кнопка "Восстановить", которая удаляет слово из словаря и восстанавливает его на странице электронного учебника

### Мини-игры "Саванна", "Аудиовызов", "Спринт", "Своя игра"

- мини-игры предназначены для изучения и повторения слов электронного учебника
- мини-игры "Саванна", "Аудиовызов" и "Спринт" повторяют одноимённые мини-игры приложения Lingualeo
- мини-игру с условным названием "Своя игра" вы придумываете сами
- слова, которые используются в мини-играх, отличаются в зависимости от того, откуда вы открываете игру: по ссылке в меню или по ссылке на странице учебника
- если мини-игра открывается по ссылке в меню, в ней есть возможность выбрать **один из шести уровней сложности**. **Уровень сложности мини-игры определяет раздел учебника, слова из которого в ней будут использоваться** 
- если мини-игра открывается по ссылке на странице учебника, она используется для повторения слов, размещённых на этой странице. В этом случае в игре нет возможности выбрать уровень сложности и используются те слова, которые размещены на данной странице учебника. Если 20 слов для мини-игры не хватает, в ней задействуются слова из предыдущих страниц учебника. 
- Если предыдущих страниц нет или недостаточно, игру можно заканчивать досрочно, когда исчерпаются все доступные слова 
- слова, которые использовались в мини-играх, открытых по ссылке на странице учебника или на странице раздела словаря "Сложные слова", попадают в раздел словаря "Изучаемые слова"

### Страница статистики

- [x] на странице статистики отображается краткосрочная статистика по результатам каждого дня и долгосрочная статистика за весь период изучения
 - [x] в краткосрочной статистике указывается количество изученных слов, процент правильных ответов и самая длинная серия правильных ответов по каждой мини-игре отдельно, а также общее количество изученных слов и процент правильных ответов за день
  - [x] в долгосрочной статистике представлены два графика. На одном из них отображается количество изученных слов за каждый день изучения, на другом - увеличение общего количества изученных слов за весь период изучения по дням.

---

### Screen sizes:
https://www.w3schools.com/browsers/browsers_display.asp - Screen Resolution Statistics
https://css-tricks.com/snippets/css/media-queries-for-standard-devices/ - Media Queries for Standard Devices
https://screensiz.es/ - sreensizes tool

**Comment by kastrubait** [comment]
![image](https://user-images.githubusercontent.com/60570588/112375533-74895c00-8cf4-11eb-82b5-4e792c2e2f13.png)

When you choose the difficulty level in the game (1, 2, 3 ... 6), then the words are taken randomly or somehow from the corresponding section of the textbook.

![image](https://user-images.githubusercontent.com/60570588/112375875-d77af300-8cf4-11eb-97bf-602a13ef835c.png)

I propose to determine for each game, based on the characteristics of the game, the minimum number of words so that the game is interesting and not too tiring. Using this value, warn the user about the lack of words and offer to return to the study.

![image](https://user-images.githubusercontent.com/60570588/112382658-2dec2f80-8cfd-11eb-87b9-cd9d68d9c715.png)

I see it like this (each type of training has a corresponding game):

![image](https://user-images.githubusercontent.com/60570588/112383998-e9619380-8cfe-11eb-8cd8-ee457904e94f.png)
