### ISSUE TITLE
[Landing] Create or find a prototype of  E-book module 

### ISSUE THREAD

**Issue by whattablackhole** [whattablackhole/rslang-archive-#8]
There are a lot of  e-books on the internet(Angular.io has an e-book).Think about how  it should look.Synchronize your ideas with Main Page Landing.

**Comment by kastrubait** [comment]
#### Prototypes can be
https://lingualeo.com/ru/dashboard
####  or
https://quizlet.com/ru/557816282/%D0%A0%D0%B0%D0%B7%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%BD%D1%8B%D0%B5-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0-flash-cards/
#### The scheme of interaction of the book with other modules
![image](https://user-images.githubusercontent.com/60570588/113485701-8d91ca00-94b7-11eb-856d-b3a24c4c5499.png)
